src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints\Json;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Vich\Uploadable()
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $vendor_code;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $thumbnail;

    /**
     * @Vich\UploadableField(mapping="product_thumbnails", fileNameProperty="thumbnail")
     */
    private $thumbnailFile;

    public function __construct()
    {

    }

    public function __toString(): string
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVendorCode(): ?string
    {
        return $this->vendor_code;
    }

    public function setVendorCode(string $vendor_code): self
    {
        $this->vendor_code = $vendor_code;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }


    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?string $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getThumbnailFile()
    {
        return $this->thumbnailFile;
    }

    /**
     * @param mixed $thumbnailFile
     * @throws \Exception
     */
    public function setThumbnailFile($thumbnailFile): void
    {
        $this->thumbnailFile = $thumbnailFile;

        if ($thumbnailFile) {
            $this->updatedAt = new \DateTime();
        }
    }
}

templates/shop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Магазин тортов{% endblock %}

{% block body %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col"><a href="/"><span class="h1">Магазин тортов</span></a></div>
                <div class="col-auto">
                    <button type="button" class="btn btn-sm mt-2 btn-light nav-drawer-open" data-toggle="modal" data-target="{% if user is not null %}#cart-modal{% else %}#login-modal{% endif %}">
                        <span class="cart-total-price">0</span> <i class="fas fa-shopping-cart"></i>
                    </button>
                    <div class="modal fade" id="cart-modal" tabindex="-1" aria-labelledby="cart-modal-label" aria-hidden="true">
                        <div class="modal-dialog modal-lg modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="cart-modal-label">Корзина</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col mt-3 shopping-cart-list">

                                        </div>
                                    </div>
                                    <div class="row mt-3">
                                        <div class="col text-left">
                                            <span class="text-muted">Доставка:</span>
                                        </div>
                                        <div class="col text-right">
                                            100,00 ₽
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col text-left">
                                            <span class="h5">Итого:</span>
                                        </div>
                                        <div class="col text-right">
                                            <span class="total-delivery-price h5">0</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                    <a href="/order" id="shopping-cart-submit" role="button" class="btn btn-primary">Оформить заказ</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    {% if user is not null %}
                        <a href="/logout" role="button" class="btn btn-sm mt-2 btn-light">Выйти</a>
                    {% else %}
                        <button type="button" class="btn btn-sm mt-2 btn-light" data-toggle="modal" data-target="#login-modal">Войти</button>
                        <div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="login-modal-label" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <form class="form-login" method="post" action="/login">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="login-modal-label">Вход для клиентов</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <label for="input-email" class="">Почта</label>
                                            <input type="email" id="email" name="email" class="form-control" aria-label="input-email" required="" autofocus="">

                                            <label for="input-password" class="mt-2">Пароль</label>
                                            <input type="password" id="input-password" name="password" class="form-control" required="">
                                            <input type="hidden" name="_csrf_token"
                                                   value="{{ csrf_token('authenticity_token') }}"
                                            >
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                            <button type="submit" class="btn btn-primary">Войти</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% block content %}{% endblock %}
        </div>
    </main>
    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted">© 2021 darkkemper</span>
        </div>
    </footer>
{% endblock %}

templates/shop/order.html.twig
{% extends 'shop/index.html.twig' %}

{% block title %}Оформление заказа{% endblock %}

{% block content %}
    <div class="row mt-4">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="padding: 0">
                    <li class="breadcrumb-item"><a href="/">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Оформление заказа</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-6">
            {% if proceed %}
                <script type="application/javascript">
                  localStorage.setItem('shopping-cart',  JSON.stringify({'products' : []}));
                  window.location = '/';
                </script>
            {% endif %}
            <h4>Ваши данные</h4>
            <br>
            <form method="post" id="order">
                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticity_token') }}">
                <input type="hidden" name="products" value="">
                <input type="hidden" class="cart-total-price" name="cart-total-price" value="">
                <p>Имя получателя и email</p>
                <div class="form-group">
                    <input type="text" class="form-control" id="name" name="name" value="{{ user.name }}">
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" autocomplete="off">
                </div>
                <p>Укажите точный адрес доставки</p>
                <div class="form-group">
                    <input type="text" class="form-control delivery-address" id="address" name="address" value="{{ user.address }}" autocomplete="off">
                </div>
                <p>Комментарий к заказу</p>
                <div class="form-group">
                    <textarea class="form-control" id="description" name="description" rows="3" placeholder="Напишите комментари к заказу"></textarea>
                    <label for="description"></label>
                </div>

                <button id="shopping-cart-submit" class="btn btn-lg btn-primary" type="submit">Оформить заказ</button>
            </form>
        </div>

        <div class="col-6">
            <div class="row">
                <div class="col">
                    <h4>Корзина</h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="m-auto position-absolute w-100 text-center shopping-cart-list-spinner d-none">
                        <span class="spinner-border text-success" role="status" aria-hidden="true"></span>
                    </div>
                    <div class="col mt-3 shopping-cart-list blur-content">

                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col text-left">
                    <span class="text-muted">Доставка:</span>
                </div>
                <div class="col text-right">
                    <span class="text-muted">100,00 ₽</span>
                </div>
            </div>
            <div class="row">
                <div class="col text-left">
                    <span class="h5">Итого:</span>
                </div>
                <div class="col text-right">
                    <span class="cart-total-price total-delivery-price h5">0</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/product-card.html.twig
<a href="/{{ product.url }}.html" class="col-3 product-card align-text-bottom {{ margin }}">
    <div class="product-image" style="background-image: url('{{ asset('uploads/files/' ~ product.thumbnail) | imagine_filter('product_card_thumb') }}')">
        {#<img src="{{ asset('uploads/files/' ~ product.thumbnail) | imagine_filter('product_card_thumb') }}" class="product-image-thumb" alt="{{ product.title }}">#}
        <div class="{% if (available) %}shopping-cart-button{% else %}shopping-cart-button-disabled{% endif %} shopping-cart-button-position"
             data-thumbnail="{{ asset('uploads/files/' ~ product.thumbnail) | imagine_filter('product_card_thumb') }}"
             data-vendor-code="{{ product.vendorCode }}"
             data-title="{{ product.title }}"
             data-url="{{ product.url }}"
             data-price="{{ product.price }}"
             data-quantity="{{ product.quantity }}"
        >
            <i class="fas fa-shopping-cart"></i>
        </div>
    </div>
    <div class="product-body mt-5">
        <div class="product-notice-{{ product.vendorCode }}">
            {% if available %}
                <span class="small text-success">В наличии {{ product.quantity }} шт</span>
            {% else %}
                <span class="small text-danger">Нет в наличии</span>
            {% endif %}
        </div>
        <div class="product-title">{{ product.title }}</div>
        <div class="product-price">
            {% if product.price is not null %}
                {{ (product.price / 100) | format_currency('RUB', locale='ru') }} <small class="text-muted">за 1 шт</small>
            {% endif %}
        </div>
    </div>
</a>

templates/shop/product.html.twig
{% extends 'shop/index.html.twig' %}

{% block title %}{{ product.title }} купить в магазине "Магазин тортов"{% endblock %}

{% block content %}
    <div class="row mt-4">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Главная</a></li>
                    <li class="breadcrumb-item">{{ product.title }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <h3>{{ product.title }}</h3>
            {% set available = true %}
            {% if product.quantity == 0 or product.quantity is null %}
                {% set available = false %}
            {% endif %}
            <span style="font-size: 1.75rem;">{{ (product.price / 100) | format_currency('RUB', locale='ru') }} <small class="text-muted">за 1 шт</small> </span>
            {% if available %}
                <div class="shopping-cart-button-main btn btn-primary text-center mt-n3"
                     data-thumbnail="{{ asset('uploads/files/' ~ product.thumbnail) | imagine_filter('product_card_thumb') }}"
                     data-vendor-code="{{ product.vendorCode }}"
                     data-title="{{ product.title }}"
                     data-url="{{ product.url }}"
                     data-price="{{ product.price }}"
                     data-quantity="{{ product.quantity }}"
                >
                    в корзину
                    <i class="fas fa-shopping-cart"></i>
                </div>&nbsp;
            {% else %}
                <div class="btn btn-dark text-center mt-n3 disabled">нет в наличии</div>
            {% endif %}

            <br><br>
            <p><strong>Описание:</strong> {{ product.description | raw}}</p>
        </div>
        <div class="col-6 text-right">
            <img src="{{ asset('uploads/files/' ~ product.thumbnail) }}" alt="{{ product.title }}" class="product-main-image"/>
        </div>
    </div>
{% endblock %}

templates/shop/products.html.twig
{% extends 'shop/index.html.twig' %}

{% block content %}
    <div class="row mt-4">
        <div class="col">
            <h3>Меню</h3>
            <br>
            <div class="row">
                {% for product in products %}
                {% set available = true %}
                {% if product.quantity == 0 or product.quantity is null %}
                    {% set available = false %}
                {% endif %}
                {% set margin = 'mb-5' %}
                {% include 'shop/product-card.html.twig' %}
                {% if (loop.index % 4) == 0 and loop.index0 != 0 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}